import { ROLE } from '../../../generated/prisma/enums.js';

export const rolePermissions: Record<ROLE, ROLE[]> = {
  [ROLE.SUPER_ADMIN]: [
    ROLE.SUPER_ADMIN,
    ROLE.NHQ_ADMIN,
    ROLE.NHQ_CHIEF_INVESTIGATOR,
    ROLE.NHQ_INVESTIGATOR,
    ROLE.NHQ_VIEWER,
    ROLE.REGIONAL_ADMIN,
    ROLE.REGIONAL_CHIEF_INVESTIGATOR,
    ROLE.REGIONAL_INVESTIGATOR,
    ROLE.REGIONAL_VIEWER,
    ROLE.DISTRICT_CHIEF_INVESTIGATOR,
    ROLE.DISTRICT_INVESTIGATOR,
    ROLE.DISTRICT_VIEWER,
    ROLE.STATION_INVESTIGATOR,
    ROLE.STATION_COMMEL,
  ],

  [ROLE.NHQ_ADMIN]: [
    ROLE.NHQ_ADMIN,
    ROLE.NHQ_CHIEF_INVESTIGATOR,
    ROLE.NHQ_INVESTIGATOR,
    ROLE.NHQ_VIEWER,
    ROLE.REGIONAL_ADMIN,
    ROLE.REGIONAL_CHIEF_INVESTIGATOR,
    ROLE.REGIONAL_INVESTIGATOR,
    ROLE.REGIONAL_VIEWER,
    ROLE.DISTRICT_CHIEF_INVESTIGATOR,
    ROLE.DISTRICT_INVESTIGATOR,
    ROLE.DISTRICT_VIEWER,
    ROLE.STATION_INVESTIGATOR,
    ROLE.STATION_COMMEL,
  ],

  [ROLE.REGIONAL_ADMIN]: [
    ROLE.REGIONAL_ADMIN,
    ROLE.REGIONAL_CHIEF_INVESTIGATOR,
    ROLE.REGIONAL_INVESTIGATOR,
    ROLE.REGIONAL_VIEWER,
    ROLE.DISTRICT_CHIEF_INVESTIGATOR,
    ROLE.DISTRICT_INVESTIGATOR,
    ROLE.DISTRICT_VIEWER,
    ROLE.STATION_INVESTIGATOR,
    ROLE.STATION_COMMEL,
  ],

  [ROLE.NHQ_CHIEF_INVESTIGATOR]: [],
  [ROLE.NHQ_INVESTIGATOR]: [],
  [ROLE.NHQ_VIEWER]: [],

  [ROLE.REGIONAL_CHIEF_INVESTIGATOR]: [],
  [ROLE.REGIONAL_INVESTIGATOR]: [],
  [ROLE.REGIONAL_VIEWER]: [],

  [ROLE.DISTRICT_CHIEF_INVESTIGATOR]: [],
  [ROLE.DISTRICT_INVESTIGATOR]: [],
  [ROLE.DISTRICT_VIEWER]: [],

  [ROLE.STATION_INVESTIGATOR]: [],
  [ROLE.STATION_COMMEL]: [],
};
